### ISSUE TITLE
Full workbench warning window missing support

### ISSUE THREAD

**Issue by yelfathi** [akamud/vscode-theme-onelight#7]
## Sample code

```
Not applicable
```

## Filename and Language selected

Not applicable

## Atom Original theme Screenshot

Not applicable

## VSCode theme Screenshot

![image](https://user-images.githubusercontent.com/9952320/27828590-23c37344-60bd-11e7-854d-ed391f52281a.png)

## Versions used

* VSCode version: 1.13.1
* Theme version: 2.0.2

## Extra information
As showed in the screenshot the color of the window is not correct.

**Comment by akamud** [comment]
Thank you for taking the time submitting this issue. It has come up before, reported in #4, since then I opened [an issue on VSCode](https://github.com/Microsoft/vscode/issues/28280) asking for better theming support on notification windows, which is already fixed, but not yet released (as of 1.13), I believe this will be in place for 1.14, but there is no way of knowing at the moment.

I'll fix this when it is available for customization and I'll report back here.

**Comment by yelfathi** [comment]
Thanks and sorry for the duplicate!

**Comment by yelfathi** [comment]
Hi @akamud it seems that it has been fixed!

**Comment by akamud** [comment]
Yes, I'll update over the next weekend. I didn't have the time to do that yet, sorry about that.
